spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/T1AcademyFirstProject
    username: postgres
    password: postgres

  mail:
    username: lexa.f1406
    password: mrfomfyltqgucatk


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: task-notification-group
      auto-offset-reset: earliest
      properties:
        trusted-packages: "*"
        max-pool-records-config: 5
    topic:
      task-status-update-topic: task-status-update-topic
    listener:
      poll-timeout: 1000