spring:
  application:
    name: FirstProjectT1Academy

  profiles:
    active: "@spring.profiles.active@"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.yandex.com
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
            fallback: false

