spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:11.13:///test_db

  mail:
    username: lexa.f1406
    password: mrfomfyltqgucatk

  kafka:
    admin:
      auto-create: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      enable:
        idempotence: false
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: task-notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.value.default.type: ru.T1Academy.FirstProject.kafka.dto.TaskStatusChangeEvent
        trusted-packages: "*"
        max-pool-records-config: 5
    topic:
      task-status-update-topic: task-status-update-topic
    listener:
      poll-timeout: 1000